### ISSUE TITLE
Uncaught exception with bad Bitcoin Config

### ISSUE THREAD

**Issue by miketwenty1** [sapio-lang/sapio-studio#30]
Environment: Mainnet
Remote Node: Yes
Bad port used by accident

Still said `connection: true`
but also got::
```
(node:56892) UnhandledPromiseRejectionWarning: Error: child exited with code 1
    at ChildProcess.<anonymous> (/home/ubuntu/sapio-studio/node_modules/await-spawn/index.js:28:21)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
(node:56892) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```

**Comment by wbobeirne** [comment]
> Remote Node: Yes
> Bad port used by accident
> Still said connection: true

Seems like this is probably #45 at work
